#!/usr/bin/env python3
"""Smart Capsule V0.1 — synthetic sensor stream simulator.

Generates realistic synthetic data for:
    - 4 pressure channels (heel, arch, ball, hallux)
    - 6-axis IMU (accel + gyro)
    - Temperature

Usage:
    python3 tools/smart_capsule_sim.py --input sample_data/capsule_session.json --output smart_capsule_data/
    python3 tools/smart_capsule_sim.py --batch sample_data/batch_sessions.csv --output smart_capsule_data/
"""

import argparse
import csv
import json
import math
import os
import random
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PRESSURE_RATE_HZ = 50
IMU_RATE_HZ = 100
TEMP_RATE_HZ = 1
SAMPLE_INTERVAL_MS = 1000 / PRESSURE_RATE_HZ  # 20 ms

NON_CLINICAL_DISCLAIMER = (
    "This is synthetic engineering data generated by the ZILFIT Smart Capsule "
    "simulator. It does not constitute a medical diagnosis, treatment "
    "recommendation, or therapeutic claim. For engineering evaluation only."
)


# ---------------------------------------------------------------------------
# Gait model (synthetic)
# ---------------------------------------------------------------------------

def _gait_cycle(phase: float, asymmetry_pct: float, roll_angle_deg: float) -> dict:
    """Synthetic gait cycle at a given phase [0, 1).

    Returns pressure, accel, gyro values for this instant.
    """
    # Heel strike at phase = 0.0, toe-off at phase = 0.6
    p_heel = max(0, 80 * math.exp(-((phase % 1.0 - 0.0) / 0.12) ** 2))
    p_arch = max(0, 60 * math.exp(-((phase % 1.0 - 0.15) / 0.15) ** 2))
    p_ball = max(0, 90 * math.exp(-((phase % 1.0 - 0.30) / 0.18) ** 2))
    p_hallux = max(0, 70 * math.exp(-((phase % 1.0 - 0.50) / 0.15) ** 2))

    # Asymmetry: reduce right side pressure slightly
    if asymmetry_pct > 0:
        factor = 1.0 - (asymmetry_pct / 100.0) * (0.5 + 0.5 * math.sin(phase * math.pi))
        p_heel *= factor
        p_arch *= factor
        p_ball *= factor
        p_hallux *= factor

    # Noise
    p_heel += random.gauss(0, 3)
    p_arch += random.gauss(0, 3)
    p_ball += random.gauss(0, 3)
    p_hallux += random.gauss(0, 3)

    # Accel: walking vertical + anterior oscillations
    accel_x = random.gauss(0, 50) + 100 * math.sin(phase * 2 * math.pi)
    accel_y = random.gauss(0, 50) + 150 * math.cos(phase * 2 * math.pi)
    accel_z = 1000 - 200 * max(0, math.sin(phase * 2 * math.pi)) + random.gauss(0, 30)

    # Gyro: roll during stance
    roll_rad = math.radians(roll_angle_deg)
    gyro_x = roll_angle_deg * 10 * math.sin(phase * 2 * math.pi) + random.gauss(0, 3)
    gyro_y = 20 * math.cos(phase * 2 * math.pi) + random.gauss(0, 5)
    gyro_z = 5 * math.sin(phase * 4 * math.pi) + random.gauss(0, 2)

    # Temp
    temp = 28.0 + 3.0 * math.sin(phase * math.pi) + random.gauss(0, 0.2)

    return {
        "p0_n": max(0, round(p_heel, 2)),
        "p1_n": max(0, round(p_arch, 2)),
        "p2_n": max(0, round(p_ball, 2)),
        "p3_n": max(0, round(p_hallux, 2)),
        "accel_x_mg": round(accel_x, 1),
        "accel_y_mg": round(accel_y, 1),
        "accel_z_mg": round(accel_z, 1),
        "gyro_x_dps": round(gyro_x, 2),
        "gyro_y_dps": round(gyro_y, 2),
        "gyro_z_dps": round(gyro_z, 2),
        "temp_c": round(temp, 2),
    }


def simulate_session(session: dict, output_dir: str) -> str:
    """Generate synthetic capsule data for one session.

    Returns path to generated CSV.
    """
    session_id = session["session_id"]
    duration_s = session.get("duration_s", 60)
    cadence_spm = session.get("cadence_spm", 110)
    asymmetry_pct = session.get("asymmetry_pct", 5.0)
    roll_angle_deg = session.get("roll_angle_deg", 3.0)

    steps_total = int(duration_s * cadence_spm / 60)
    step_duration_s = 60.0 / cadence_spm

    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, f"session_{session_id}.csv")

    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "timestamp_ms", "p0_n", "p1_n", "p2_n", "p3_n",
            "accel_x_mg", "accel_y_mg", "accel_z_mg",
            "gyro_x_dps", "gyro_y_dps", "gyro_z_dps", "temp_c",
        ])

        total_samples = int(duration_s * PRESSURE_RATE_HZ)
        for i in range(total_samples):
            t_s = i / PRESSURE_RATE_HZ
            t_ms = int(t_s * 1000)
            step_phase = (t_s / step_duration_s) % 1.0
            row = _gait_cycle(step_phase, asymmetry_pct, roll_angle_deg)
            writer.writerow([
                t_ms,
                row["p0_n"], row["p1_n"], row["p2_n"], row["p3_n"],
                row["accel_x_mg"], row["accel_y_mg"], row["accel_z_mg"],
                row["gyro_x_dps"], row["gyro_y_dps"], row["gyro_z_dps"],
                row["temp_c"],
            ])
        f.flush()
        os.fsync(f.fileno())

    file_size = os.path.getsize(output_path)
    print(f"  Session {session_id}: {total_samples} samples, {duration_s}s, "
          f"{steps_total} steps → {output_path} ({file_size} bytes)")
    return output_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Smart Capsule V0.1 synthetic sensor simulator."
    )
    parser.add_argument("--input", help="Path to session JSON")
    parser.add_argument("--batch", help="Path to batch sessions CSV")
    parser.add_argument("--output", required=True, help="Output directory for CSV files")
    args = parser.parse_args()

    if not args.input and not args.batch:
        print("ERROR: --input or --batch required.", file=sys.stderr)
        sys.exit(1)

    files_generated = []

    if args.input:
        with open(args.input, "r") as f:
            session = json.load(f)
        path = simulate_session(session, args.output)
        files_generated.append(path)

    if args.batch:
        with open(args.batch, "r") as f:
            reader = csv.DictReader(f)
            for row in reader:
                session = {
                    "session_id": row["session_id"],
                    "duration_s": int(row.get("duration_s", 60)),
                    "cadence_spm": int(row.get("cadence_spm", 110)),
                    "asymmetry_pct": float(row.get("asymmetry_pct", 5.0)),
                    "roll_angle_deg": float(row.get("roll_angle_deg", 3.0)),
                }
                path = simulate_session(session, args.output)
                files_generated.append(path)

    print(f"\nGenerated {len(files_generated)} session file(s).")


if __name__ == "__main__":
    main()
