#!/usr/bin/env python3
"""Smart Capsule V0.1 — gait metric report generator.

Computes from a capsule CSV session:
    steps_estimate, heel_strike_events, toe_off_events,
    pressure_balance, pronation_signal_estimate,
    fatigue_signal_estimate, recommendation_for_next_insole_design

Usage:
    python3 tools/smart_capsule_report.py --input smart_capsule_data/session_CAP_001.csv --output report.json
    python3 tools/smart_capsule_report.py --batch smart_capsule_data/ --output weekly_summary.json
"""

import argparse
import csv
import json
import math
import os
import sys
from collections import defaultdict
from glob import glob

NON_CLINICAL_DISCLAIMER = (
    "This report is an engineering gait-metric summary generated by the ZILFIT "
    "Smart Capsule simulator. It does not constitute a medical diagnosis, "
    "treatment recommendation, or therapeutic claim. All metrics are provided "
    "for doctor and private tester evaluation only."
)

PRESSURE_THRESHOLD_N = 15.0  # Heel/toe pressure threshold for event detection


def _read_csv(csv_path: str) -> list:
    rows = []
    with open(csv_path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def _safe_float(val):
    try:
        return float(val)
    except (TypeError, ValueError):
        return None

def compute_metrics(rows: list) -> dict:
    """Extract gait metrics from capsule CSV rows."""
    if not rows:
        return {"error": "Empty session data"}

    # Filter out malformed rows
    clean = []
    for r in rows:
        vals = {k: _safe_float(r.get(k)) for k in r}
        if all(vals.get(k) is not None for k in ["p0_n", "p1_n", "p2_n", "p3_n", "gyro_x_dps"]):
            clean.append(vals)

    if not clean:
        return {"error": "No valid rows in session data"}

    p0 = [r["p0_n"] for r in clean]
    p1 = [r["p1_n"] for r in clean]
    p2 = [r["p2_n"] for r in clean]
    p3 = [r["p3_n"] for r in clean]
    gyro_x = [r["gyro_x_dps"] for r in clean]
    times = [int(r["timestamp_ms"]) for r in clean]

    # Steps estimate: count heel pressure peaks above threshold
    heel_strikes = []
    toe_offs = []
    in_heel = False
    in_toe = False

    for i in range(len(p0)):
        t = times[i]
        if p0[i] > PRESSURE_THRESHOLD_N and not in_heel:
            in_heel = True
            heel_strikes.append(t)
        elif p0[i] < PRESSURE_THRESHOLD_N * 0.5 and in_heel:
            in_heel = False

        if p3[i] > PRESSURE_THRESHOLD_N and not in_toe:
            in_toe = True
            toe_offs.append(t)
        elif p3[i] < PRESSURE_THRESHOLD_N * 0.5 and in_toe:
            in_toe = False

    steps_estimate = len(heel_strikes)

    # Pressure balance: rearfoot (P0+P1) vs forefoot (P2+P3)
    mean_rear = (sum(p0) + sum(p1)) / (2 * len(p0)) if p0 else 0
    mean_fore = (sum(p2) + sum(p3)) / (2 * len(p3)) if p3 else 0
    pressure_balance = round(mean_rear / mean_fore, 3) if mean_fore > 0 else 1.0

    # Pronation signal: mean gyro roll during stance (gyro_x)
    stance_mask = [1 if p0[i] > PRESSURE_THRESHOLD_N * 0.3 else 0 for i in range(len(p0))]
    stance_gyro = [gyro_x[i] for i in range(len(gyro_x)) if stance_mask[i]]
    pronation_signal = round(sum(stance_gyro) / len(stance_gyro), 2) if stance_gyro else 0.0

    # Fatigue signal: drift in heel pressure peak amplitude over session
    n_segments = 5
    seg_len = len(p0) // n_segments
    seg_peaks = []
    for seg in range(n_segments):
        start = seg * seg_len
        end = start + seg_len
        if start < len(p0):
            seg_peaks.append(max(p0[start:end]))
    if len(seg_peaks) >= 2:
        fatigue_signal = round((seg_peaks[0] - seg_peaks[-1]) / max(seg_peaks) * 100, 2)
    else:
        fatigue_signal = 0.0

    # Recommendation
    recommendation = _heuristic_recommendation(
        pressure_balance, pronation_signal, fatigue_signal
    )

    return {
        "steps_estimate": steps_estimate,
        "heel_strike_events": heel_strikes[:20],  # Truncate for readability
        "toe_off_events": toe_offs[:20],
        "pressure_balance": pressure_balance,
        "pronation_signal_estimate": pronation_signal,
        "fatigue_signal_estimate": fatigue_signal,
        "recommendation_for_next_insole_design": recommendation,
        "non_clinical_disclaimer": NON_CLINICAL_DISCLAIMER,
    }


def _heuristic_recommendation(balance: float, roll: float, fatigue: float) -> str:
    """V0.1 heuristic for insole design feedback."""
    reasons = []

    if balance > 1.5:
        reasons.append("Increase forefoot cushioning")
    elif balance < 0.7:
        reasons.append("Increase heel cushioning")

    if abs(roll) > 8.0:
        reasons.append("Increase medial/lateral stability geometry")

    if fatigue > 8.0:
        reasons.append("Adjust arch support density for fatigue resistance")

    if not reasons:
        reasons.append("Maintain current geometry; continue evaluation")

    return "; ".join(reasons)


def process_single(input_path: str, output_path: str) -> dict:
    """Process one session CSV and write report JSON."""
    rows = _read_csv(input_path)
    metrics = compute_metrics(rows)
    metrics["session_csv"] = os.path.basename(input_path)

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(metrics, f, indent=2)

    return metrics


def process_batch(input_dir: str, output_path: str) -> dict:
    """Process all session CSVs in a directory."""
    csv_files = sorted(glob(os.path.join(input_dir, "session_*.csv")))
    if not csv_files:
        csv_files = sorted(glob(os.path.join(input_dir, "*.csv")))

    all_sessions = []
    for cf in csv_files:
        rows = _read_csv(cf)
        metrics = compute_metrics(rows)
        metrics["session_csv"] = os.path.basename(cf)
        all_sessions.append(metrics)

    # Aggregate
    steps = [s["steps_estimate"] for s in all_sessions]
    balances = [s["pressure_balance"] for s in all_sessions]
    rolls = [s["pronation_signal_estimate"] for s in all_sessions]
    fatigues = [s["fatigue_signal_estimate"] for s in all_sessions]

    summary = {
        "session_count": len(all_sessions),
        "total_steps": sum(steps),
        "avg_steps_per_session": round(sum(steps) / len(steps), 1) if steps else 0,
        "avg_pressure_balance": round(sum(balances) / len(balances), 3) if balances else 0,
        "avg_pronation_signal_deg": round(sum(rolls) / len(rolls), 2) if rolls else 0,
        "avg_fatigue_signal_pct": round(sum(fatigues) / len(fatigues), 2) if fatigues else 0,
        "sessions": all_sessions,
        "non_clinical_disclaimer": NON_CLINICAL_DISCLAIMER,
    }

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(summary, f, indent=2)

    return summary


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Smart Capsule V0.1 report generator."
    )
    parser.add_argument("--input", help="Path to single session CSV")
    parser.add_argument("--batch", help="Directory of session CSVs")
    parser.add_argument("--output", required=True, help="Output JSON path")
    args = parser.parse_args()

    if args.input:
        result = process_single(args.input, args.output)
        print(json.dumps(result, indent=2))

    elif args.batch:
        result = process_batch(args.batch, args.output)
        print(f"Batch report: {result['session_count']} sessions, "
              f"{result['total_steps']} total steps")

    else:
        print("ERROR: --input or --batch required.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
